version: "3.3"

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=147258369aA!
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./db:/var/lib/mysql

  maildev:
    image: soulteary/maildev
    container_name: maildev
    restart: always
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-php-myadmin
    ports:
      - "8082:80"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: spring

  javadocservice:
    image: java-doc
    container_name: java-doc-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - db
      - maildev
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/java_doc?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 147258369aA!

#volumes:
#  -db: