version: "3"

services:
  server:
    build: ./
    restart: on-failure
    extra_hosts:
      - "docker.for.mac.host.internal:host-gateway"
    ports:
      - "3001:3001"
#    volumes:
#      - "/home/dev/documents:/documents"